export const GENERIC_ERROR_CODES = {
  GENERIC_BAD_REQUEST: 'GENERIC_BAD_REQUEST',
  GENERIC_UNAUTHORIZED: 'GENERIC_UNAUTHORIZED',
  GENERIC_FORBIDDEN: 'GENERIC_FORBIDDEN',
  GENERIC_NOT_FOUND: 'GENERIC_NOT_FOUND',
  GENERIC_CONFLICT: 'GENERIC_CONFLICT',
  GENERIC_UNPROCESSABLE: 'GENERIC_UNPROCESSABLE',
  GENERIC_INTERNAL_SERVER_ERROR: 'GENERIC_INTERNAL_SERVER_ERROR',
  GENERIC_VALIDATION_FAILED: 'GENERIC_VALIDATION_FAILED',
} as const;

export const DATABASE_ERROR_CODES = {
  DATABASE_UNIQUE_VIOLATION: 'DATABASE_UNIQUE_VIOLATION',
  DATABASE_FOREIGN_KEY_VIOLATION: 'DATABASE_FOREIGN_KEY_VIOLATION',
  DATABASE_NOT_NULL_VIOLATION: 'DATABASE_NOT_NULL_VIOLATION',
} as const;

export type GenericErrorCode = (typeof GENERIC_ERROR_CODES)[keyof typeof GENERIC_ERROR_CODES];
export type DatabaseErrorCode = (typeof DATABASE_ERROR_CODES)[keyof typeof DATABASE_ERROR_CODES];
