export const PLATFORM_ERROR_CODES = {
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_STORAGE_ERROR: 'FILE_STORAGE_ERROR',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',
  FILE_QUOTA_EXCEEDED: 'FILE_QUOTA_EXCEEDED',
  FILE_FORBIDDEN: 'FILE_FORBIDDEN',
  FILE_DIMENSIONS_EXCEEDED: 'FILE_DIMENSIONS_EXCEEDED',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_FORBIDDEN: 'NOTIFICATION_FORBIDDEN',
} as const;
