import { Module } from '@nestjs/common';

import {
  AdminAllowedEmailRepository,
  AiProviderApiKeyRepository,
  AiSessionMessageRepository,
  AiTaskSessionRepository,
  AuthTokenRepository,
  BillingPeriodRepository,
  BusinessProfileRepository,
  BusinessTransactionRepository,
  ChatMessageRepository,
  ConsultantOnboardingAnswerRepository,
  ConsultantOnboardingRepository,
  ConsultantProfileRepository,
  ConsultantSkillExamAnswerRepository,
  ConsultantSkillExamQuestionRepository,
  ConsultantSkillExamRepository,
  ConsultantSkillRepository,
  ConsultantSkillScoreRepository,
  ConsultantTransactionRepository,
  FileRepository,
  IdempotencyKeyRepository,
  InvoiceLineItemRepository,
  InvoiceRepository,
  NotificationRepository,
  OnboardingQuestionRepository,
  ProjectActivityRepository,
  ProjectAiContextRepository,
  ProjectChatSessionRepository,
  ProjectMemberRepository,
  ProjectRepository,
  ProjectRequiredSkillRepository,
  ProjectStatusHistoryRepository,
  SkillRepository,
  TaskAttachmentRepository,
  TaskCodeService,
  TaskDisputeRepository,
  TaskHistoryRepository,
  TaskRepository,
  TaskResultAttachmentRepository,
  TaskResultRepository,
  TransactionNumberService,
  UserRepository,
  UserSessionRepository,
  UserSsoProviderRepository,
  WebhookEventRepository,
} from './repositories';
import { UnitOfWorkService } from './unit-of-work.service';

const repositories = [
  AdminAllowedEmailRepository,
  UserRepository,
  AuthTokenRepository,
  UserSsoProviderRepository,
  UserSessionRepository,
  BusinessProfileRepository,
  SkillRepository,
  ConsultantProfileRepository,
  ConsultantSkillRepository,
  ProjectRepository,
  ProjectRequiredSkillRepository,
  ProjectActivityRepository,
  ProjectStatusHistoryRepository,
  ProjectMemberRepository,
  ProjectChatSessionRepository,
  ChatMessageRepository,
  ProjectAiContextRepository,
  TaskRepository,
  TaskAttachmentRepository,
  TaskDisputeRepository,
  TaskHistoryRepository,
  TaskResultRepository,
  TaskResultAttachmentRepository,
  AiTaskSessionRepository,
  AiSessionMessageRepository,
  BillingPeriodRepository,
  InvoiceRepository,
  InvoiceLineItemRepository,
  ConsultantTransactionRepository,
  BusinessTransactionRepository,
  WebhookEventRepository,
  FileRepository,
  NotificationRepository,
  IdempotencyKeyRepository,
  AiProviderApiKeyRepository,
  // Onboarding
  ConsultantOnboardingRepository,
  ConsultantOnboardingAnswerRepository,
  OnboardingQuestionRepository,
  // Skill exams
  ConsultantSkillExamRepository,
  ConsultantSkillExamQuestionRepository,
  ConsultantSkillExamAnswerRepository,
  ConsultantSkillScoreRepository,
];

@Module({
  providers: [UnitOfWorkService, TransactionNumberService, TaskCodeService, ...repositories],
  exports: [UnitOfWorkService, TransactionNumberService, TaskCodeService],
})
export class UnitOfWorkModule {}
