import { DATABASE_ERROR_CODES, GENERIC_ERROR_CODES } from '@plys/libraries/shared-kernel';

export const IDENTITY_ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_ALREADY_USED: 'AUTH_TOKEN_ALREADY_USED',
  AUTH_DEVICE_MISMATCH: 'AUTH_DEVICE_MISMATCH',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  AUTH_EMAIL_PENDING_VERIFICATION: 'AUTH_EMAIL_PENDING_VERIFICATION',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_OAUTH_STATE_INVALID: 'AUTH_OAUTH_STATE_INVALID',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_SSO_EXCHANGE_INVALID: 'AUTH_SSO_EXCHANGE_INVALID',
  ADMIN_AUTH_OTP_INVALID: 'ADMIN_AUTH_OTP_INVALID',
  ADMIN_AUTH_OTP_LOCKED: 'ADMIN_AUTH_OTP_LOCKED',
  ADMIN_AUTH_RESEND_LIMIT: 'ADMIN_AUTH_RESEND_LIMIT',
  ADMIN_AUTH_EMAIL_NOT_ALLOWED: 'ADMIN_AUTH_EMAIL_NOT_ALLOWED',
  ADMIN_ALLOWED_EMAIL_ALREADY_EXISTS: 'ADMIN_ALLOWED_EMAIL_ALREADY_EXISTS',
  ADMIN_ALLOWED_EMAIL_REVOKED: 'ADMIN_ALLOWED_EMAIL_REVOKED',
  ADMIN_ALLOWED_EMAIL_NOT_FOUND: 'ADMIN_ALLOWED_EMAIL_NOT_FOUND',
  ADMIN_ALLOWED_EMAIL_CANNOT_REVOKE_SELF: 'ADMIN_ALLOWED_EMAIL_CANNOT_REVOKE_SELF',
  CONSULTANT_ONBOARDING_BLOCKED: 'CONSULTANT_ONBOARDING_BLOCKED',
} as const;

export const ERROR_CODES = {
  ...GENERIC_ERROR_CODES,
  ...DATABASE_ERROR_CODES,
  ...IDENTITY_ERROR_CODES,
} as const;

export type IdentityErrorCode = (typeof IDENTITY_ERROR_CODES)[keyof typeof IDENTITY_ERROR_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
