import { DATABASE_ERROR_CODES, GENERIC_ERROR_CODES } from '@plys/libraries/shared-kernel';

/** AI provider keys, chat sessions, project AI context. */
export const AI_PROVIDER_ERROR_CODES = {
  AI_PROVIDER_KEY_NOT_CONFIGURED: 'AI_PROVIDER_KEY_NOT_CONFIGURED',
  AI_PROVIDER_KEY_NOT_FOUND: 'AI_PROVIDER_KEY_NOT_FOUND',
  AI_PROVIDER_KEY_ACTIVE_REQUIRES_REPLACEMENT: 'AI_PROVIDER_KEY_ACTIVE_REQUIRES_REPLACEMENT',
  AI_PROVIDER_KEY_CIPHER_FAILED: 'AI_PROVIDER_KEY_CIPHER_FAILED',
  CHAT_SESSION_NOT_FOUND: 'CHAT_SESSION_NOT_FOUND',
  CHAT_SESSION_NOT_ACTIVE: 'CHAT_SESSION_NOT_ACTIVE',
  CHAT_SESSION_MODE_NOT_ALLOWED: 'CHAT_SESSION_MODE_NOT_ALLOWED',
  CHAT_SESSION_MESSAGE_LIMIT_EXCEEDED: 'CHAT_SESSION_MESSAGE_LIMIT_EXCEEDED',
  AI_CONTEXT_NOT_FOUND: 'AI_CONTEXT_NOT_FOUND',
  AI_CONTEXT_DERIVED_HTML_FORBIDDEN: 'AI_CONTEXT_DERIVED_HTML_FORBIDDEN',
  BUSINESS_PROFILE_NOT_FOUND: 'BUSINESS_PROFILE_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
} as const;

export const ERROR_CODES = {
  ...GENERIC_ERROR_CODES,
  ...DATABASE_ERROR_CODES,
  ...AI_PROVIDER_ERROR_CODES,
} as const;

export type AiProviderErrorCode =
  (typeof AI_PROVIDER_ERROR_CODES)[keyof typeof AI_PROVIDER_ERROR_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
