import { Module } from '@nestjs/common';

import { ProjectsUnitOfWorkService } from './projects-unit-of-work.service';
import {
  AdminAllowedEmailRepository,
  AiProviderApiKeyRepository,
  AiSessionMessageRepository,
  AiTaskSessionRepository,
  AuthTokenRepository,
  BillingPeriodRepository,
  BusinessProfileRepository,
  BusinessTransactionRepository,
  ChatMessageRepository,
  ConsultantOnboardingAnswerRepository,
  ConsultantOnboardingRepository,
  ConsultantProfileRepository,
  ConsultantSkillExamAnswerRepository,
  ConsultantSkillExamQuestionRepository,
  ConsultantSkillExamRepository,
  ConsultantSkillRepository,
  ConsultantSkillScoreRepository,
  ConsultantTransactionRepository,
  FileRepository,
  IdempotencyKeyRepository,
  InvoiceLineItemRepository,
  InvoiceRepository,
  NotificationRepository,
  OnboardingQuestionRepository,
  ProjectActivityRepository,
  ProjectAiContextRepository,
  ProjectChatSessionRepository,
  ProjectMemberRepository,
  ProjectRepository,
  ProjectRequiredSkillRepository,
  ProjectStatusHistoryRepository,
  SkillRepository,
  TaskAttachmentRepository,
  TaskCodeService,
  TaskDisputeRepository,
  TaskHistoryRepository,
  TaskRepository,
  TaskResultAttachmentRepository,
  TaskResultRepository,
  TaskReviewRepository,
  TransactionNumberService,
  UserRepository,
  UserSessionRepository,
  UserSsoProviderRepository,
  WebhookEventRepository,
} from './repositories';

const repositories = [
  AdminAllowedEmailRepository,
  UserRepository,
  AuthTokenRepository,
  UserSsoProviderRepository,
  UserSessionRepository,
  BusinessProfileRepository,
  SkillRepository,
  ConsultantProfileRepository,
  ConsultantSkillRepository,
  ProjectRepository,
  ProjectRequiredSkillRepository,
  ProjectActivityRepository,
  ProjectStatusHistoryRepository,
  ProjectMemberRepository,
  ProjectChatSessionRepository,
  ChatMessageRepository,
  ProjectAiContextRepository,
  TaskRepository,
  TaskAttachmentRepository,
  TaskDisputeRepository,
  TaskHistoryRepository,
  TaskResultRepository,
  TaskResultAttachmentRepository,
  TaskReviewRepository,
  AiTaskSessionRepository,
  AiSessionMessageRepository,
  BillingPeriodRepository,
  InvoiceRepository,
  InvoiceLineItemRepository,
  ConsultantTransactionRepository,
  BusinessTransactionRepository,
  WebhookEventRepository,
  FileRepository,
  NotificationRepository,
  IdempotencyKeyRepository,
  AiProviderApiKeyRepository,
  ConsultantOnboardingRepository,
  ConsultantOnboardingAnswerRepository,
  OnboardingQuestionRepository,
  ConsultantSkillExamRepository,
  ConsultantSkillExamQuestionRepository,
  ConsultantSkillExamAnswerRepository,
  ConsultantSkillScoreRepository,
];

@Module({
  providers: [
    ProjectsUnitOfWorkService,
    TransactionNumberService,
    TaskCodeService,
    ...repositories,
  ],
  exports: [
    ProjectsUnitOfWorkService,
    TransactionNumberService,
    TaskCodeService,
    BusinessProfileRepository,
    ConsultantProfileRepository,
    ConsultantSkillRepository,
  ],
})
export class ProjectsUnitOfWorkModule {}
