export enum ApplicationStatus {
  PENDING_PROFILE = 'PENDING_PROFILE',
  GENERATING_QUESTIONS = 'GENERATING_QUESTIONS',
  IN_INTERVIEW = 'IN_INTERVIEW',
  INTERVIEW_SUBMITTED = 'INTERVIEW_SUBMITTED',
  RUNNING_COPYLEAKS = 'RUNNING_COPYLEAKS',
  COPYLEAKS_FAILED = 'COPYLEAKS_FAILED',
  PENDING_AI_EVALUATION = 'PENDING_AI_EVALUATION',
  PENDING_ADMIN_EVALUATION = 'PENDING_ADMIN_EVALUATION',
  PENDING_FINAL_DECISION = 'PENDING_FINAL_DECISION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
