export enum OnboardingStatus {
  PENDING_BASIC_INFO = 'PENDING_BASIC_INFO',
  IN_INTERVIEW = 'IN_INTERVIEW',
  INTERVIEW_SUBMITTED = 'INTERVIEW_SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum OnboardingDecision {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
