import { DATABASE_ERROR_CODES, GENERIC_ERROR_CODES } from '@plys/libraries/shared-kernel';

export const FINANCE_ERROR_CODES = {
  PAYMENT_INSUFFICIENT_BALANCE: 'PAYMENT_INSUFFICIENT_BALANCE',
  PAYMENT_STRIPE_NOT_CONNECTED: 'PAYMENT_STRIPE_NOT_CONNECTED',
  PAYMENT_TRANSFER_FAILED: 'PAYMENT_TRANSFER_FAILED',
  PAYMENT_CHECKOUT_FAILED: 'PAYMENT_CHECKOUT_FAILED',
  PAYMENT_MINIMUM_WITHDRAWAL: 'PAYMENT_MINIMUM_WITHDRAWAL',
  PAYMENT_TRANSACTION_NOT_FOUND: 'PAYMENT_TRANSACTION_NOT_FOUND',
  PAYMENT_TRANSACTION_NOT_OWNED: 'PAYMENT_TRANSACTION_NOT_OWNED',
  PAYMENT_TRANSACTION_NOT_PENDING: 'PAYMENT_TRANSACTION_NOT_PENDING',
  BILLING_PERIOD_NOT_FOUND: 'BILLING_PERIOD_NOT_FOUND',
  BILLING_INVOICE_NOT_FOUND: 'BILLING_INVOICE_NOT_FOUND',
  BILLING_INVOICE_ALREADY_PAID: 'BILLING_INVOICE_ALREADY_PAID',
  BILLING_INVOICE_NOT_OWNED: 'BILLING_INVOICE_NOT_OWNED',
  BILLING_CHECKOUT_FAILED: 'BILLING_CHECKOUT_FAILED',
  BUSINESS_PROFILE_NOT_FOUND: 'BUSINESS_PROFILE_NOT_FOUND',
  CONSULTANT_PROFILE_NOT_FOUND: 'CONSULTANT_PROFILE_NOT_FOUND',
} as const;

export const ERROR_CODES = {
  ...GENERIC_ERROR_CODES,
  ...DATABASE_ERROR_CODES,
  ...FINANCE_ERROR_CODES,
} as const;

export type FinanceErrorCode = (typeof FINANCE_ERROR_CODES)[keyof typeof FINANCE_ERROR_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
