import { DATABASE_ERROR_CODES, GENERIC_ERROR_CODES } from '@plys/libraries/shared-kernel';

/** Internal Hub admin: onboarding questions, consultant review, cross-domain reads. */
export const INTERNAL_ADMIN_ERROR_CODES = {
  ONBOARDING_QUESTION_NOT_FOUND: 'ONBOARDING_QUESTION_NOT_FOUND',
  ONBOARDING_QUESTION_INVALID_OPTIONS: 'ONBOARDING_QUESTION_INVALID_OPTIONS',
  ONBOARDING_QUESTION_TYPE_CHANGE_FORBIDDEN: 'ONBOARDING_QUESTION_TYPE_CHANGE_FORBIDDEN',
  ONBOARDING_REORDER_SET_MISMATCH: 'ONBOARDING_REORDER_SET_MISMATCH',
  CONSULTANT_ONBOARDING_NOT_FOUND: 'CONSULTANT_ONBOARDING_NOT_FOUND',
  CONSULTANT_ONBOARDING_INVALID_STATUS: 'CONSULTANT_ONBOARDING_INVALID_STATUS',
  SKILL_EXAM_NOT_FOUND: 'SKILL_EXAM_NOT_FOUND',
  AI_CONTEXT_NOT_FOUND: 'AI_CONTEXT_NOT_FOUND',
  BUSINESS_PROFILE_NOT_FOUND: 'BUSINESS_PROFILE_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
} as const;

export const ERROR_CODES = {
  ...GENERIC_ERROR_CODES,
  ...DATABASE_ERROR_CODES,
  ...INTERNAL_ADMIN_ERROR_CODES,
} as const;

export type InternalAdminErrorCode =
  (typeof INTERNAL_ADMIN_ERROR_CODES)[keyof typeof INTERNAL_ADMIN_ERROR_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
