import { ActivePlatform, UserRole } from '@database/enums';

export type SupportedLocale = 'en' | 'tr';

export const SUPPORTED_LOCALES: readonly SupportedLocale[] = ['en', 'tr'] as const;
export const DEFAULT_LOCALE: SupportedLocale = 'en';

export interface IRequestContext {
  /** Unique identifier for the request, generated by RequestContextMiddleware. */
  requestId: string;
  /** User identifier, or `null` if not authenticated. */
  userId: string | null;
  /** User email address, or `null` if not authenticated. */
  email: string | null;
  /** User role (e.g. `ADMIN_PLATFORM`, `USER`), or `null` if not authenticated. */
  userRole: UserRole | null;
  /** Session identifier (e.g. from `x-session-id` header), or `null` if not provided. */
  sessionId: string | null;
  /** Active platform (e.g. `business`, `consultant`, `admin_platform`), or `null` if not set. */
  activePlatform: ActivePlatform | null;
  /** Caller-supplied device identifier (e.g. from `x-device-id` header), or `null` if not provided. */
  deviceId: string | null;
  /** Client IP address, derived from `x-forwarded-for` or `req.ip`. */
  ipAddress: string;
  /** User-Agent header value, or `null` if missing. */
  userAgent: string | null;
  /** Request path (e.g. `/api/v1/users`) */
  path: string;
  /** HTTP method (e.g. `GET`, `POST`, etc.) */
  method: string;
  /** User's preferred language. */
  lang: SupportedLocale;
  /**
   * Caller-supplied IANA timezone from the `x-timezone` header (e.g.
   * `Asia/Ho_Chi_Minh`). `null` when omitted or invalid — downstream
   * callers should fall back to UTC.
   */
  timezone: string | null;
}
