/**
 * Machine-readable error codes included in every error response as `error_code`.
 * Clients use these for programmatic error handling independent of locale/language.
 *
 * Convention: SCREAMING_SNAKE_CASE, grouped by domain prefix.
 * Adding a new error:
 *   1. Add the constant here.
 *   2. Pass it as `errorCode` when throwing TranslatableException.
 *   3. Add the corresponding i18n key to src/i18n/en/error.json.
 */
export const ERROR_CODES = {
  // ─── Generic ──────────────────────────────────────────────────────────────
  GENERIC_BAD_REQUEST: 'GENERIC_BAD_REQUEST',
  GENERIC_UNAUTHORIZED: 'GENERIC_UNAUTHORIZED',
  GENERIC_FORBIDDEN: 'GENERIC_FORBIDDEN',
  GENERIC_NOT_FOUND: 'GENERIC_NOT_FOUND',
  GENERIC_CONFLICT: 'GENERIC_CONFLICT',
  GENERIC_UNPROCESSABLE: 'GENERIC_UNPROCESSABLE',
  GENERIC_INTERNAL_SERVER_ERROR: 'GENERIC_INTERNAL_SERVER_ERROR',
  GENERIC_VALIDATION_FAILED: 'GENERIC_VALIDATION_FAILED',

  // ─── Auth ─────────────────────────────────────────────────────────────────
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_ALREADY_USED: 'AUTH_TOKEN_ALREADY_USED',
  AUTH_DEVICE_MISMATCH: 'AUTH_DEVICE_MISMATCH',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  AUTH_EMAIL_PENDING_VERIFICATION: 'AUTH_EMAIL_PENDING_VERIFICATION',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_OAUTH_STATE_INVALID: 'AUTH_OAUTH_STATE_INVALID',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_SSO_EXCHANGE_INVALID: 'AUTH_SSO_EXCHANGE_INVALID',

  // ─── Business Profile ────────────────────────────────────────────────────
  BUSINESS_PROFILE_ALREADY_EXISTS: 'BUSINESS_PROFILE_ALREADY_EXISTS',
  BUSINESS_PROFILE_NOT_FOUND: 'BUSINESS_PROFILE_NOT_FOUND',

  // ─── Consultant Profile ──────────────────────────────────────────────────
  CONSULTANT_PROFILE_ALREADY_EXISTS: 'CONSULTANT_PROFILE_ALREADY_EXISTS',
  CONSULTANT_PROFILE_NOT_FOUND: 'CONSULTANT_PROFILE_NOT_FOUND',

  // ─── Project ──────────────────────────────────────────────────────────────
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_FORBIDDEN: 'PROJECT_FORBIDDEN',
  PROJECT_INVALID_STATUS_TRANSITION: 'PROJECT_INVALID_STATUS_TRANSITION',
  PROJECT_REQUIRES_TASKS_FOR_CONFIGURED: 'PROJECT_REQUIRES_TASKS_FOR_CONFIGURED',
  PROJECT_SKILL_NOT_FOUND: 'PROJECT_SKILL_NOT_FOUND',
  PROJECT_CANNOT_BE_EDITED: 'PROJECT_CANNOT_BE_EDITED',
  PROJECT_CANNOT_PUBLISH: 'PROJECT_CANNOT_PUBLISH',
  PROJECT_INSUFFICIENT_BALANCE: 'PROJECT_INSUFFICIENT_BALANCE',
  PROJECT_INVALID_TASK_PRICE: 'PROJECT_INVALID_TASK_PRICE',
  PROJECT_RECALL_TRANSACTION_NOT_FOUND: 'PROJECT_RECALL_TRANSACTION_NOT_FOUND',
  PROJECT_CANNOT_BE_DELETED: 'PROJECT_CANNOT_BE_DELETED',
  PROJECT_CODE_ALREADY_EXISTS: 'PROJECT_CODE_ALREADY_EXISTS',

  // ─── Database ─────────────────────────────────────────────────────────────
  DATABASE_UNIQUE_VIOLATION: 'DATABASE_UNIQUE_VIOLATION',
  DATABASE_FOREIGN_KEY_VIOLATION: 'DATABASE_FOREIGN_KEY_VIOLATION',
  DATABASE_NOT_NULL_VIOLATION: 'DATABASE_NOT_NULL_VIOLATION',

  // ─── Business Payments ─────────────────────────────────────────────────────
  PAYMENT_INSUFFICIENT_BALANCE: 'PAYMENT_INSUFFICIENT_BALANCE',
  PAYMENT_STRIPE_NOT_CONNECTED: 'PAYMENT_STRIPE_NOT_CONNECTED',
  PAYMENT_TRANSFER_FAILED: 'PAYMENT_TRANSFER_FAILED',
  PAYMENT_CHECKOUT_FAILED: 'PAYMENT_CHECKOUT_FAILED',
  PAYMENT_MINIMUM_WITHDRAWAL: 'PAYMENT_MINIMUM_WITHDRAWAL',
  PAYMENT_TRANSACTION_NOT_FOUND: 'PAYMENT_TRANSACTION_NOT_FOUND',
  PAYMENT_TRANSACTION_NOT_OWNED: 'PAYMENT_TRANSACTION_NOT_OWNED',
  PAYMENT_TRANSACTION_NOT_PENDING: 'PAYMENT_TRANSACTION_NOT_PENDING',

  // ─── Billing ──────────────────────────────────────────────────────────────
  BILLING_PERIOD_NOT_FOUND: 'BILLING_PERIOD_NOT_FOUND',
  BILLING_INVOICE_NOT_FOUND: 'BILLING_INVOICE_NOT_FOUND',
  BILLING_INVOICE_ALREADY_PAID: 'BILLING_INVOICE_ALREADY_PAID',
  BILLING_INVOICE_NOT_OWNED: 'BILLING_INVOICE_NOT_OWNED',
  BILLING_CHECKOUT_FAILED: 'BILLING_CHECKOUT_FAILED',

  // ─── Tasks ────────────────────────────────────────────────────────────────
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_INVALID_STATUS_TRANSITION: 'TASK_INVALID_STATUS_TRANSITION',
  TASK_ALREADY_ASSIGNED: 'TASK_ALREADY_ASSIGNED',
  TASK_PROJECT_NOT_IN_PROGRESS: 'TASK_PROJECT_NOT_IN_PROGRESS',
  TASK_EVIDENCE_NOT_FOUND: 'TASK_EVIDENCE_NOT_FOUND',
  TASK_EVIDENCE_FORBIDDEN: 'TASK_EVIDENCE_FORBIDDEN',
  TASK_EVIDENCE_NOT_ASSIGNEE: 'TASK_EVIDENCE_NOT_ASSIGNEE',
  TASK_EVIDENCE_FILE_NOT_OWNED: 'TASK_EVIDENCE_FILE_NOT_OWNED',
  TASK_EVIDENCE_EMPTY_UPDATE: 'TASK_EVIDENCE_EMPTY_UPDATE',
  TASK_CONSULTANT_ALREADY_IN_PROGRESS: 'TASK_CONSULTANT_ALREADY_IN_PROGRESS',

  // ─── Files ────────────────────────────────────────────────────────────────
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_STORAGE_ERROR: 'FILE_STORAGE_ERROR',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',
  FILE_QUOTA_EXCEEDED: 'FILE_QUOTA_EXCEEDED',
  FILE_FORBIDDEN: 'FILE_FORBIDDEN',
  FILE_DIMENSIONS_EXCEEDED: 'FILE_DIMENSIONS_EXCEEDED',

  // ─── Notifications ────────────────────────────────────────────────────────
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_FORBIDDEN: 'NOTIFICATION_FORBIDDEN',

  // ─── AI provider key vault ────────────────────────────────────────────────
  AI_PROVIDER_KEY_NOT_CONFIGURED: 'AI_PROVIDER_KEY_NOT_CONFIGURED',
  AI_PROVIDER_KEY_NOT_FOUND: 'AI_PROVIDER_KEY_NOT_FOUND',
  AI_PROVIDER_KEY_ACTIVE_REQUIRES_REPLACEMENT: 'AI_PROVIDER_KEY_ACTIVE_REQUIRES_REPLACEMENT',
  AI_PROVIDER_KEY_CIPHER_FAILED: 'AI_PROVIDER_KEY_CIPHER_FAILED',

  // ─── Project chat sessions ────────────────────────────────────────────────
  CHAT_SESSION_NOT_FOUND: 'CHAT_SESSION_NOT_FOUND',
  CHAT_SESSION_NOT_ACTIVE: 'CHAT_SESSION_NOT_ACTIVE',
  CHAT_SESSION_MODE_NOT_ALLOWED: 'CHAT_SESSION_MODE_NOT_ALLOWED',
  CHAT_SESSION_MESSAGE_LIMIT_EXCEEDED: 'CHAT_SESSION_MESSAGE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
