export enum SkillExamStatus {
  GENERATING_QUESTIONS = 'GENERATING_QUESTIONS',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  RUNNING_COPYLEAKS = 'RUNNING_COPYLEAKS',
  COPYLEAKS_FAILED = 'COPYLEAKS_FAILED',
  RUNNING_AI_EVAL = 'RUNNING_AI_EVAL',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
}

export enum SkillExamFailReason {
  LOW_SCORE = 'LOW_SCORE',
  COPYLEAKS_FAILED = 'COPYLEAKS_FAILED',
}

export const SKILL_EXAM_IN_PROGRESS_STATUSES: readonly SkillExamStatus[] = [
  SkillExamStatus.GENERATING_QUESTIONS,
  SkillExamStatus.IN_PROGRESS,
  SkillExamStatus.SUBMITTED,
  SkillExamStatus.RUNNING_COPYLEAKS,
  SkillExamStatus.RUNNING_AI_EVAL,
];
