name: 'Install & Build (dev)'
description: 'Install dependencies and run the build script'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build
      shell: bash
      run: pnpm run build
