/** Error codes thrown by @plys/libraries/common-nest infrastructure (not domain services). */
export const AUTH_ERROR_CODES = {
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_DEVICE_MISMATCH: 'AUTH_DEVICE_MISMATCH',
  ADMIN_AUTH_RESEND_LIMIT: 'ADMIN_AUTH_RESEND_LIMIT',
} as const;

export const FILE_ERROR_CODES = {
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_STORAGE_ERROR: 'FILE_STORAGE_ERROR',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',
  FILE_DIMENSIONS_EXCEEDED: 'FILE_DIMENSIONS_EXCEEDED',
} as const;

export const GATEWAY_INFRA_ERROR_CODES = {
  IDEMPOTENCY_KEY_BODY_MISMATCH: 'IDEMPOTENCY_KEY_BODY_MISMATCH',
  AI_CONTEXT_DERIVED_HTML_FORBIDDEN: 'AI_CONTEXT_DERIVED_HTML_FORBIDDEN',
} as const;

export const AI_PROVIDER_KEY_ERROR_CODES = {
  AI_PROVIDER_KEY_NOT_CONFIGURED: 'AI_PROVIDER_KEY_NOT_CONFIGURED',
  AI_PROVIDER_KEY_NOT_FOUND: 'AI_PROVIDER_KEY_NOT_FOUND',
  AI_PROVIDER_KEY_ACTIVE_REQUIRES_REPLACEMENT: 'AI_PROVIDER_KEY_ACTIVE_REQUIRES_REPLACEMENT',
  AI_PROVIDER_KEY_CIPHER_FAILED: 'AI_PROVIDER_KEY_CIPHER_FAILED',
} as const;
