export const CONSULTANT_APPLICATION_QUEUE = 'consultant-application';

export const CONSULTANT_APPLICATION_JOBS = {
  GENERATE_SKILL_QUESTIONS: 'GENERATE_SKILL_QUESTIONS',
  RUN_COPYLEAKS_EVALUATION: 'RUN_COPYLEAKS_EVALUATION',
  RUN_AI_EVALUATION: 'RUN_AI_EVALUATION',
} as const;

export const TOTAL_QUESTIONS = 30;
export const COMMUNICATION_QUESTION_COUNT = 10;
export const SKILL_BASED_QUESTION_COUNT = 15;
export const SYSTEM_KNOWLEDGE_QUESTION_COUNT = 5;

export const COPYLEAKS_PASS_MAX_AI_SCORE = 30;
export const FINAL_SCORE_AI_WEIGHT = 0.6;
export const FINAL_SCORE_ADMIN_WEIGHT = 0.4;
export const PASS_THRESHOLD = 80;

export const BLOCK_MONTHS = 3;
