import { DATABASE_ERROR_CODES, GENERIC_ERROR_CODES } from '@plys/libraries/shared-kernel';

/** Consultant profiles, onboarding, skill exams, explore, membership, tasks (Lonaos domain). */
export const CONSULTANT_SERVICE_ERROR_CODES = {
  CONSULTANT_PROFILE_ALREADY_EXISTS: 'CONSULTANT_PROFILE_ALREADY_EXISTS',
  CONSULTANT_PROFILE_NOT_FOUND: 'CONSULTANT_PROFILE_NOT_FOUND',
  CONSULTANT_ONBOARDING_NOT_FOUND: 'CONSULTANT_ONBOARDING_NOT_FOUND',
  CONSULTANT_ONBOARDING_BLOCKED: 'CONSULTANT_ONBOARDING_BLOCKED',
  CONSULTANT_ONBOARDING_INVALID_STATUS: 'CONSULTANT_ONBOARDING_INVALID_STATUS',
  CONSULTANT_ONBOARDING_INCOMPLETE_ANSWERS: 'CONSULTANT_ONBOARDING_INCOMPLETE_ANSWERS',
  CONSULTANT_ONBOARDING_NOT_APPROVED: 'CONSULTANT_ONBOARDING_NOT_APPROVED',
  CONSULTANT_ONBOARDING_INVALID_ANSWER: 'CONSULTANT_ONBOARDING_INVALID_ANSWER',
  CONSULTANT_ONBOARDING_ANSWERS_COVERAGE: 'CONSULTANT_ONBOARDING_ANSWERS_COVERAGE',
  SKILL_EXAM_NOT_FOUND: 'SKILL_EXAM_NOT_FOUND',
  SKILL_EXAM_USER_BANNED: 'SKILL_EXAM_USER_BANNED',
  SKILL_EXAM_ALREADY_PASSED: 'SKILL_EXAM_ALREADY_PASSED',
  SKILL_EXAM_ALREADY_IN_PROGRESS: 'SKILL_EXAM_ALREADY_IN_PROGRESS',
  SKILL_EXAM_COOLDOWN_ACTIVE: 'SKILL_EXAM_COOLDOWN_ACTIVE',
  SKILL_EXAM_PARALLEL_LIMIT_REACHED: 'SKILL_EXAM_PARALLEL_LIMIT_REACHED',
  SKILL_EXAM_INVALID_STATUS: 'SKILL_EXAM_INVALID_STATUS',
  SKILL_EXAM_INCOMPLETE_ANSWERS: 'SKILL_EXAM_INCOMPLETE_ANSWERS',
  SKILL_EXAM_NOT_READY: 'SKILL_EXAM_NOT_READY',
  SKILL_EXAM_EXPIRED: 'SKILL_EXAM_EXPIRED',
  SKILL_EXAM_TAKING_BLOCKED: 'SKILL_EXAM_TAKING_BLOCKED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_NOT_JOINABLE: 'PROJECT_NOT_JOINABLE',
  PROJECT_ALREADY_MEMBER: 'PROJECT_ALREADY_MEMBER',
  PROJECT_MEMBERSHIP_BANNED: 'PROJECT_MEMBERSHIP_BANNED',
  PROJECT_FULL: 'PROJECT_FULL',
  PROJECT_SKILL_MATCH_INSUFFICIENT: 'PROJECT_SKILL_MATCH_INSUFFICIENT',
  PROJECT_CONCURRENT_LIMIT_REACHED: 'PROJECT_CONCURRENT_LIMIT_REACHED',
  PROJECT_NOT_MEMBER: 'PROJECT_NOT_MEMBER',
  PROJECT_LEAVE_BLOCKED_BY_ACTIVE_TASKS: 'PROJECT_LEAVE_BLOCKED_BY_ACTIVE_TASKS',
  PROJECT_SKILL_NOT_FOUND: 'PROJECT_SKILL_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_NOT_CLAIMABLE: 'TASK_NOT_CLAIMABLE',
  TASK_NOT_OWNED_BY_CONSULTANT: 'TASK_NOT_OWNED_BY_CONSULTANT',
  TASK_INVALID_STATE_FOR_UNASSIGN: 'TASK_INVALID_STATE_FOR_UNASSIGN',
  TASK_INVALID_STATE_FOR_SUBMIT: 'TASK_INVALID_STATE_FOR_SUBMIT',
  TASK_REVIEW_NOT_FOUND: 'TASK_REVIEW_NOT_FOUND',
  TASK_REVIEW_FORBIDDEN: 'TASK_REVIEW_FORBIDDEN',
  TASK_REVIEW_ALREADY_VOTED: 'TASK_REVIEW_ALREADY_VOTED',
  TASK_REVIEW_ROUND_CLOSED: 'TASK_REVIEW_ROUND_CLOSED',
  TASK_REVIEW_INVALID_DECISION: 'TASK_REVIEW_INVALID_DECISION',
  TASK_REVIEW_INSUFFICIENT_REVIEWERS: 'TASK_REVIEW_INSUFFICIENT_REVIEWERS',
} as const;

export const ERROR_CODES = {
  ...GENERIC_ERROR_CODES,
  ...DATABASE_ERROR_CODES,
  ...CONSULTANT_SERVICE_ERROR_CODES,
} as const;

export type ConsultantServiceErrorCode =
  (typeof CONSULTANT_SERVICE_ERROR_CODES)[keyof typeof CONSULTANT_SERVICE_ERROR_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
