import { DATABASE_ERROR_CODES, GENERIC_ERROR_CODES } from '@plys/libraries/shared-kernel';

/** Business profiles, onboarding, projects, tasks (Ployos domain). */
export const BUSINESS_SERVICE_ERROR_CODES = {
  BUSINESS_PROFILE_ALREADY_EXISTS: 'BUSINESS_PROFILE_ALREADY_EXISTS',
  BUSINESS_PROFILE_NOT_FOUND: 'BUSINESS_PROFILE_NOT_FOUND',
  BUSINESS_PROFILE_TAX_ID_ALREADY_EXISTS: 'BUSINESS_PROFILE_TAX_ID_ALREADY_EXISTS',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_FORBIDDEN: 'PROJECT_FORBIDDEN',
  PROJECT_INVALID_STATUS_TRANSITION: 'PROJECT_INVALID_STATUS_TRANSITION',
  PROJECT_REQUIRES_TASKS_FOR_CONFIGURED: 'PROJECT_REQUIRES_TASKS_FOR_CONFIGURED',
  PROJECT_SKILL_NOT_FOUND: 'PROJECT_SKILL_NOT_FOUND',
  PROJECT_CANNOT_BE_EDITED: 'PROJECT_CANNOT_BE_EDITED',
  PROJECT_CANNOT_PUBLISH: 'PROJECT_CANNOT_PUBLISH',
  PROJECT_INSUFFICIENT_BALANCE: 'PROJECT_INSUFFICIENT_BALANCE',
  PROJECT_INVALID_TASK_PRICE: 'PROJECT_INVALID_TASK_PRICE',
  PROJECT_RECALL_TRANSACTION_NOT_FOUND: 'PROJECT_RECALL_TRANSACTION_NOT_FOUND',
  PROJECT_CANNOT_BE_DELETED: 'PROJECT_CANNOT_BE_DELETED',
  PROJECT_CODE_ALREADY_EXISTS: 'PROJECT_CODE_ALREADY_EXISTS',
  PROJECT_MINIMUM_TASKS_NOT_MET: 'PROJECT_MINIMUM_TASKS_NOT_MET',
  PROJECT_MINIMUM_COST_NOT_MET: 'PROJECT_MINIMUM_COST_NOT_MET',
  PROJECT_PRICE_GATE_FAILED: 'PROJECT_PRICE_GATE_FAILED',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_INVALID_STATUS_TRANSITION: 'TASK_INVALID_STATUS_TRANSITION',
  TASK_ATTACHMENT_NOT_FOUND: 'TASK_ATTACHMENT_NOT_FOUND',
  TASK_ATTACHMENT_FORBIDDEN: 'TASK_ATTACHMENT_FORBIDDEN',
  TASK_ATTACHMENT_FILE_NOT_OWNED: 'TASK_ATTACHMENT_FILE_NOT_OWNED',
  TASK_ATTACHMENT_INVALID_STATUS: 'TASK_ATTACHMENT_INVALID_STATUS',
  AI_SYNC_TASK_REJECTED: 'AI_SYNC_TASK_REJECTED',
  AI_SYNC_SKILL_NOT_FOUND: 'AI_SYNC_SKILL_NOT_FOUND',
  AI_CONTEXT_NOT_FOUND: 'AI_CONTEXT_NOT_FOUND',
} as const;

export const ERROR_CODES = {
  ...GENERIC_ERROR_CODES,
  ...DATABASE_ERROR_CODES,
  ...BUSINESS_SERVICE_ERROR_CODES,
} as const;

export type BusinessServiceErrorCode =
  (typeof BUSINESS_SERVICE_ERROR_CODES)[keyof typeof BUSINESS_SERVICE_ERROR_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
