import { DATABASE_ERROR_CODES, GENERIC_ERROR_CODES } from '@plys/libraries/shared-kernel';

/** Task review workflow (Internal Hub reviewers). */
export const TASK_REVIEWER_ERROR_CODES = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_NOT_OWNED_BY_CONSULTANT: 'TASK_NOT_OWNED_BY_CONSULTANT',
  TASK_REVIEW_NOT_FOUND: 'TASK_REVIEW_NOT_FOUND',
  TASK_REVIEW_FORBIDDEN: 'TASK_REVIEW_FORBIDDEN',
  TASK_REVIEW_ALREADY_VOTED: 'TASK_REVIEW_ALREADY_VOTED',
  TASK_REVIEW_ROUND_CLOSED: 'TASK_REVIEW_ROUND_CLOSED',
  TASK_REVIEW_INVALID_DECISION: 'TASK_REVIEW_INVALID_DECISION',
  TASK_REVIEW_INSUFFICIENT_REVIEWERS: 'TASK_REVIEW_INSUFFICIENT_REVIEWERS',
} as const;

export const ERROR_CODES = {
  ...GENERIC_ERROR_CODES,
  ...DATABASE_ERROR_CODES,
  ...TASK_REVIEWER_ERROR_CODES,
} as const;

export type TaskReviewerErrorCode =
  (typeof TASK_REVIEWER_ERROR_CODES)[keyof typeof TASK_REVIEWER_ERROR_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
